inherit_from: .rubocop_todo.yml
# アスキー以外のコメントを許可（日本語でのコメントが可能になる）
AsciiComments:
  Enabled: false
# クラスにコメントを残さないでも良い
Documentation:
  Enabled: false
# compact styleの適用も許可する
ClassAndModuleChildren:
  Enabled: false
#ABCMetricSizeのチェックの基準値を20にする
Metrics/AbcSize:
  Max: 20
